function [ResultMedian] = mediana7x7(InputImg)
    ResultMedian = InputImg;
    for i=4:size(InputImg,2)-3
        for j=4:size(InputImg,1)-3
            W = [InputImg(i-3, j-3), InputImg(i-2, j-3), InputImg(i-1, j-3), InputImg(i, j-3), InputImg(i+1, j-3), InputImg(i+2, j-3), InputImg(i+3, j-3),...
                 InputImg(i-3, j-2), InputImg(i-2, j-2), InputImg(i-1, j-2), InputImg(i, j-2), InputImg(i+1, j-2), InputImg(i+2, j-2), InputImg(i+3, j-2),...
                 InputImg(i-3, j-1), InputImg(i-2, j-1), InputImg(i-1, j-1), InputImg(i, j-1), InputImg(i+1, j-1), InputImg(i+2, j-1), InputImg(i+3, j-1),...
                 InputImg(i-3, j), InputImg(i-2, j), InputImg(i-1, j), InputImg(i, j), InputImg(i+1, j), InputImg(i+2, j), InputImg(i+3, j),...
                 InputImg(i-3, j+1), InputImg(i-2, j+1), InputImg(i-1, j+1), InputImg(i, j+1), InputImg(i+1, j+1), InputImg(i+2, j+1), InputImg(i+3, j+1),...
                 InputImg(i-3, j+2), InputImg(i-2, j+2), InputImg(i-1, j+2), InputImg(i, j+2), InputImg(i+1, j+2), InputImg(i+2, j+2), InputImg(i+3, j+2),...
                 InputImg(i-3, j+3), InputImg(i-2, j+3), InputImg(i-1, j+3), InputImg(i, j+3), InputImg(i+1, j+3), InputImg(i+2, j+3), InputImg(i+3, j+3)];
            Wsort = sort(W);
            ResultMedian(i,j) = Wsort(25);
        end
    end
end

